spring.application.name=POC-Security-JWT
spring.datasource.url=jdbc:h2:mem:poc-jwt-db
spring.datasource.driverClassName=org.h2.Driver
spring.h2.console.enabled=true
server.port=9090
springdoc.swagger-ui.path=/swagger-ui
springdoc.api-docs.path=/api-docs
